### PR TITLE
init multi-llm

### PR DESCRIPTION
**Pull request by zhangxu0307**
support using different LLM APIs for different roles and componets

### CODE REVIEW

**Comment by liqul** [comment]
Add unit test

**Comment by zhangxu0307** [comment]
> Add unit test

added

**Comment by liqul** [comment]
@Jack-Q modify openai llm impl

**Comment by zhangxu0307** [comment]
> @Jack-Q modify openai llm impl

just fixed this issue in a hacky way.

**Review by liqul — APPROVED** [review]

**Pull request merged**
