### PR TITLE
update glm api models

### PR DESCRIPTION
**Pull request by zRzRzRzRzRzRzR**
This PR supports the latest model of the [GLM](https://open.bigmodel.cn/) series. Including Embedding models and LLM.
The GLM-4 model has been tested and can effectively complete the tasks in the demo.

### CODE REVIEW

**Comment by zRzRzRzRzRzRzR** [comment]
> @zRzRzRzRzRzRzR please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information. 请阅读以下贡献者许可协议（CLA）。如果您同意CLA，请回复以下信息。
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options: 选项： 
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.（默认-未指定公司）我对提交的内容拥有知识产权的唯一所有权，我不是在为我的雇主工作的过程中提交内容。
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.(when我在为我的雇主工作的过程中提交（或我的雇主根据合同或适用法律对我的提交内容拥有知识产权）。我已获得雇主的许可，可以代表雇主提交资料并签署本协议。通过在下面签名，定义的术语“您”包括我和我的雇主。
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
> 贡献者许可协议

@microsoft-github-policy-service agree

**Comment by zRzRzRzRzRzRzR** [comment]
do I need to write `zhipuai` to requirements.txt to pass pytest?

**Comment by liqul** [comment]
> do I need to write `zhipuai` to requirements.txt to pass pytest?

No, the framework should not depend on any LLM library. Please see my previous comment.

**Comment by zRzRzRzRzRzRzR** [comment]
I did not modify the `requirements.txt` dependencies in this PR. However, if you use glm api, you need to install the dependencies of this model, so I counterfeit the [Qwen](https://github.com/microsoft/TaskWeaver/blob/main/website/docs/llms/qwen.md) readme and wrote a corresponding readme of `website`.
In pytest, I added a test for the glm model embedding, but it failed due to the lack of the `zhipuai`  lib.

**Comment by liqul** [comment]
> I did not modify the `requirements.txt` dependencies in this PR. However, if you use glm api, you need to install the dependencies of this model, so I counterfeit the [Qwen](https://github.com/microsoft/TaskWeaver/blob/main/website/docs/llms/qwen.md) readme and wrote a corresponding readme of `website`. In pytest, I added a test for the glm model embedding, but it failed due to the lack of the `zhipuai` lib.

I have a inline comment for you in the code. Since the unit test is not going to run in the pipeline (see the decorator), the reason that caused this failure is that you put `import zhipuai` at the head of the python script. Please first move the import line in zhipuai.py into the __init__ function and then import the service instead of the lib in the unit test file.

**Review by liqul — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
