### PR TITLE
new web scraper plugin

### PR DESCRIPTION
**Pull request by glufy10**
so i created this web scraper and i don't now if it is working.

I used the web search plugin and did some changes to create this one

### CODE REVIEW

**Comment by glufy10** [comment]
@microsoft-github-policy-service agree

**Comment by glufy10** [comment]
@microsoft-github-policy-service agree

**Comment by liqul** [comment]
> so i created this web scraper and i don't now if it is working.
> 
> I used the web search plugin and did some changes to create this one

So, you haven't try it at your local env? Will take some time to investigate it. Could you also add a section in `plugins/README.md` to introduce this plugin?

**Comment by glufy10** [comment]
i have a 2013 laptop so i can't run local llm  and i am a student so i don't have money to get a open ai api key

**Comment by liqul** [comment]
> i have a 2013 laptop so i can't run local llm and i am a student so i don't have money to get a open ai api key

I will do a test with your plugin later. Just FYI, there are free apis to use such as Google's Gemini Pro.

**Comment by liqul** [comment]
I downloaded your plugin files, but could not get it run successfully. First of all, you didn't follow our syntax in defining the plugin as described [here](https://microsoft.github.io/TaskWeaver/docs/plugin/plugin_intro). I would suggest you start from a simple one and then add more logic to its function. Secondly, I can see the main changes made to the existing `web_search` plugin is scrapping the page content. We considered this before but we didn't do it because the content could be too large to put into the prompt. 

So, my suggestion is that you first test it locally by using a free LLM api and check if the workflow is as expected. 

FYI - there are also tools like [this](https://python.langchain.com/docs/use_cases/web_scraping#research-automation) that can be used directly. You may want to take a look at it and see if it can already solve some of your problems.

**Pull request closed without merging**
